<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>psu.se411</groupId>
  <artifactId>se411lab4</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  
  <name>se411lab4</name>
  <description>This project is lab 4</description>
  <url>https://github.com/omarmeleraky/SE411_Labs_223211469</url>
  
  <licenses>
  <license>
  <name>Apache License 2.0</name>
  <url>https://www.apache.org/licenses/LICENSE-2.0</url>
  </license>
  </licenses>
  
  <organization>
  <name>SE411-LAB-4</name>
  <url>https://mycompanyUrl.dom</url>
  </organization>
  
  <developers>
  <developer>
  <name>Omar Eleraky</name>
  <email>223211469@psu.edu.sa</email>
  </developer>
  </developers>
  
  <dependencies>
  <dependency>
          <groupId>org.openjfx</groupId>
          <artifactId>javafx-controls</artifactId>
          <version>23</version>
    </dependency>
  </dependencies>
  <build>
  <plugins>
  <plugin>
          <groupId>org.openjfx</groupId>
          <artifactId>javafx-maven-plugin</artifactId>
          <version>0.0.8</version>
          <configuration>
               <mainClass>psu.se411.se411lab4.MainApp</mainClass>
          </configuration>
      </plugin>

  </plugins>
  </build>
  
</project>